# Generated by Django 3.1.3 on 2022-07-13 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_question_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='auther',
            new_name='author',
        ),
    ]
